/* Generated by Myra UI Editor at 11/16/2017 2:38:36 AM */

using Myra.Graphics2D;
using Myra.Graphics2D.UI;

namespace Myra.Samples.CustomUIStylesheet
{
	public partial class AllWidgets: HorizontalSplitPane
	{
		public AllWidgets()
		{
			BuildUI();

			_button.Image = new Drawable(DefaultAssets.UISpritesheet["icon-star"]);
			_imageButton.Image = new Drawable(DefaultAssets.UISpritesheet["icon-star-outline"]);

			_button.Up += (sender, args) =>
			{
				var debugWindow = new DebugOptionsDialog();
				debugWindow.ShowModal(Desktop);
			};

			_textButton.Up += (sender, args) =>
			{
				var debugWindow = new DebugOptionsDialog();
				debugWindow.ShowModal(Desktop);
			};

			_imageButton.Up += (sender, args) =>
			{
				var debugWindow = new DebugOptionsDialog();
				debugWindow.ShowModal(Desktop);
			};

			var tree = new Tree
			{
				HasRoot = false,
				GridPositionX = 1,
				GridPositionY = 9
			};
			var node1 = tree.AddSubNode("node1");
			var node2 = node1.AddSubNode("node2");
			var node3 = node2.AddSubNode("node3");
			node3.AddSubNode("node4");
			node3.AddSubNode("node5");
			node2.AddSubNode("node6");
			_gridRight.Widgets.Add(tree);
		}
	}
}